DROP SEQUENCE NOSEQ;
DROP TABLE BOARD;

CREATE SEQUENCE NOSEQ;

CREATE TABLE BOARD(
	MNO NUMBER PRIMARY KEY,
	NAME VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	MDATE DATE NOT NULL
);

INSERT INTO BOARD
VALUES (NOSEQ.NEXTVAL, '관리자', '테스트 글이당', '아아테스트!1234', SYSDATE);

SELECT MNO, NAME, TITLE, CONTENT, MDATE
FROM BOARD
ORDER BY MNO DESC;
